version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: dai-transactions-app
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dai-transcations
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
